version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - apt-get install -y unzip
      - npm install


  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.html ./aws.gif ./1.png ./back.jpg
      - npm run build

   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server

cache:
  paths:
    - node_modules/
